name: billsplit
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.2.4
  figma_squircle: ^0.5.3
  line_icons: ^2.0.0
  iconsax: ^0.0.8
  http: ^0.13.4
  flutter_bloc: ^8.0.0
  screenshot: ^2.1.0
  go_router: 7.0.2
  flutter_launcher_icons: "^0.13.1"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 900

flutter_icons:
  image_path: "assets/icons/bs_logo.png" 
  android: true
  ios: true
